'use client'

import { useCallback, useEffect, useMemo, useState } from 'react'
import { motion } from 'framer-motion'
import { Cloud, CloudRain, CloudSun, Droplets, LocateFixed, MapPin, Search, Snowflake, Sun, Sunrise, Sunset, Thermometer, Wind, X, Zap } from 'lucide-react'

type WeatherData = { current: { temperature_2m: number; relative_humidity_2m: number; apparent_temperature: number; is_day: number; precipitation: number; weather_code: number; wind_speed_10m: number; uv_index: number }; hourly: { time: string[]; temperature_2m: number[]; precipitation_probability: number[]; weather_code: number[] }; daily: { time: string[]; weather_code: number[]; temperature_2m_max: number[]; temperature_2m_min: number[]; sunrise: string[]; sunset: string[]; uv_index_max: number[] } }
type Place = { name: string; country: string; latitude: number; longitude: number; admin1?: string }
const FALLBACK: Place = { name: 'Jakarta', country: 'Indonesia', admin1: 'DKI Jakarta', latitude: -6.2, longitude: 106.816666 }
const formatTime = (value: string) => new Date(value).toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit' })
const formatDay = (value: string, index: number) => index === 0 ? 'Hari ini' : new Date(`${value}T12:00:00`).toLocaleDateString('id-ID', { weekday: 'short' })
function weatherInfo(code: number, day = 1) { if (code === 0) return { label: day ? 'Langit cerah' : 'Malam cerah', sentence: day ? 'Cahaya matahari mendominasi hari ini.' : 'Malam cerah dan tenang.', icon: Sun, tone: 'clear' }; if ([1, 2, 3, 45, 48].includes(code)) return { label: code === 3 ? 'Mendung' : 'Berawan sebagian', sentence: 'Awan bergerak tanpa banyak gangguan.', icon: code === 3 ? Cloud : CloudSun, tone: 'cloudy' }; if ([95, 96, 99].includes(code)) return { label: 'Badai petir', sentence: 'Waspadai petir dan hujan deras.', icon: Zap, tone: 'storm' }; if ([71, 73, 75, 77, 85, 86].includes(code)) return { label: 'Salju', sentence: 'Suhu dingin dengan kemungkinan salju.', icon: Snowflake, tone: 'snow' }; return { label: 'Hujan', sentence: 'Hujan mungkin turun sepanjang hari.', icon: CloudRain, tone: 'rain' } }

export default function WeatherApp() {
  const [place, setPlace] = useState(FALLBACK), [weather, setWeather] = useState<WeatherData | null>(null), [query, setQuery] = useState(''), [results, setResults] = useState<Place[]>([]), [loading, setLoading] = useState(true), [searching, setSearching] = useState(false), [locating, setLocating] = useState(false), [error, setError] = useState(''), [updated, setUpdated] = useState('')
  const loadWeather = useCallback(async (next: Place) => { setLoading(true); setError(''); try { const params = new URLSearchParams({ latitude: String(next.latitude), longitude: String(next.longitude), current: 'temperature_2m,relative_humidity_2m,apparent_temperature,is_day,precipitation,weather_code,wind_speed_10m,uv_index', hourly: 'temperature_2m,precipitation_probability,weather_code', daily: 'weather_code,temperature_2m_max,temperature_2m_min,sunrise,sunset,uv_index_max', timezone: 'auto', forecast_days: '7' }); const response = await fetch(`https://api.open-meteo.com/v1/forecast?${params}`); if (!response.ok) throw new Error(); const data = await response.json(); setWeather(data); setPlace(next); const stamp = new Date().toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit' }); setUpdated(stamp); localStorage.setItem('atmos-weather-cache', JSON.stringify({ data, place: next, updated: stamp })) } catch { const cached = localStorage.getItem('atmos-weather-cache'); if (cached) { const saved = JSON.parse(cached); setWeather(saved.data); setPlace(saved.place); setUpdated(saved.updated); setError('Offline — menampilkan data terakhir.') } else setError('Cuaca belum tersedia. Cari kota untuk memulai.') } finally { setLoading(false) } }, [])
  useEffect(() => { const cached = localStorage.getItem('atmos-weather-cache'); if (cached) { try { const saved = JSON.parse(cached); setWeather(saved.data); setPlace(saved.place); setUpdated(saved.updated) } catch {} } loadWeather(cached ? JSON.parse(cached).place : FALLBACK) }, [loadWeather])
  useEffect(() => { if ('serviceWorker' in navigator) navigator.serviceWorker.register('/sw.js').catch(() => {}) }, [])
  async function searchPlaces(value: string) { setQuery(value); if (value.trim().length < 2) return setResults([]); setSearching(true); try { const res = await fetch(`https://nominatim.openstreetmap.org/search?format=jsonv2&addressdetails=1&limit=5&q=${encodeURIComponent(value)}`); const data = await res.json(); setResults(data.map((item: any) => ({ name: item.name || item.display_name.split(',')[0], country: item.address?.country || '', admin1: item.address?.state, latitude: Number(item.lat), longitude: Number(item.lon) }))) } finally { setSearching(false) } }
  function useLocation() { if (!navigator.geolocation) return setError('Lokasi tidak didukung browser ini.'); setLocating(true); navigator.geolocation.getCurrentPosition(async ({ coords }) => { const next: Place = { name: 'Lokasi saat ini', country: '', latitude: coords.latitude, longitude: coords.longitude }; try { const res = await fetch(`https://nominatim.openstreetmap.org/reverse?format=jsonv2&lat=${coords.latitude}&lon=${coords.longitude}`); const data = await res.json(); next.name = data.address?.city || data.address?.town || data.address?.village || next.name; next.country = data.address?.country || '' } catch {} await loadWeather(next); setLocating(false) }, () => { setError('Izin lokasi ditolak.'); setLocating(false) }) }
  const info = weatherInfo(weather?.current.weather_code ?? 0, weather?.current.is_day ?? 1), Icon = info.icon, start = weather ? Math.max(0, weather.hourly.time.findIndex(t => new Date(t) >= new Date())) : 0, hours = weather?.hourly.time.slice(start, start + 24) ?? [], max = weather?.daily.temperature_2m_max[0] ?? 0, min = weather?.daily.temperature_2m_min[0] ?? 0
  const range = useMemo(() => Math.max(1, max - min), [max, min])
  return <main className={`weather-shell ${info.tone}`}><div className="weather-page">
    <header className="topbar"><div className="masthead"><p>ATMOS / CUACA HARI INI</p><h1>{place.name}</h1><span>{place.admin1 || place.country}</span></div><div className="top-actions"><div className="search-box"><Search aria-hidden="true" /><label className="sr-only" htmlFor="city-search">Cari kota</label><input id="city-search" value={query} onChange={e => searchPlaces(e.target.value)} placeholder="Cari kota" autoComplete="off" />{(results.length > 0 || searching) && <div className="search-results">{searching ? <span>Mencari...</span> : results.map(result => <button key={`${result.latitude}`} onClick={() => { loadWeather(result); setQuery(''); setResults([]) }}><MapPin aria-hidden="true" /><span><b>{result.name}</b><small>{[result.admin1, result.country].filter(Boolean).join(', ')}</small></span></button>)}</div>}</div><button className="plain-button" onClick={useLocation} disabled={locating} aria-label="Gunakan lokasi saya"><LocateFixed aria-hidden="true" /> <span>Lokasi saya</span></button></div></header>
    {error && <div className="notice" role="status">{error}<button onClick={() => setError('')} aria-label="Tutup"><X aria-hidden="true" /></button></div>}
    <section className="hero"><div><p className="section-kicker">Kondisi saat ini</p><motion.div key={weather?.current.temperature_2m} initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="temperature">{loading ? '—' : Math.round(weather?.current.temperature_2m ?? 0)}<sup>°</sup></motion.div></div><div className="hero-side">{loading ? <><span className="loading-line loading-icon" aria-hidden="true" /><span className="loading-line loading-title" aria-label="Memuat kondisi cuaca" /><span className="loading-line" aria-hidden="true" /><span className="loading-line loading-wide" aria-hidden="true" /></> : <><Icon aria-hidden="true" /><strong>{info.label}</strong><span>Terasa {Math.round(weather?.current.apparent_temperature ?? 0)}° · Tinggi {Math.round(max)}° · Rendah {Math.round(min)}°</span></>}</div></section>
    <div className="uv-row"><span>UV index</span><strong>{loading ? '—' : weather?.current.uv_index.toFixed(0)}</strong><span>{(weather?.current.uv_index ?? 0) > 5 ? 'Perlindungan diperlukan' : 'Rendah hari ini'}</span></div>
    <section className="details"><div><Droplets aria-hidden="true" /><p>Kelembapan</p><strong>{loading ? '—' : `${weather?.current.relative_humidity_2m}%`}</strong></div><div><Wind aria-hidden="true" /><p>Angin</p><strong>{loading ? '—' : `${Math.round(weather?.current.wind_speed_10m ?? 0)} km/j`}</strong></div><div><Thermometer aria-hidden="true" /><p>Curah hujan</p><strong>{loading ? '—' : `${weather?.current.precipitation} mm`}</strong></div></section>
    <section className="forecast-section"><div className="section-title"><h2>Prakiraan per jam</h2><span>24 jam</span></div><div className="hour-line">{hours.map((time, index) => { const i = start + index; const chance = weather?.hourly.precipitation_probability[i] ?? 0; const hourlyInfo = weatherInfo(weather?.hourly.weather_code[i] ?? 0); return <div className="hour-item" key={time}><span>{index === 0 ? 'Kini' : formatTime(time)}</span>{chance > 20 && <i title={`Peluang hujan ${chance}%`}>●</i>}<strong>{Math.round(weather?.hourly.temperature_2m[i] ?? 0)}°</strong><small>{chance}%</small></div> })}</div></section>
    <section className="forecast-section days-section"><div className="section-title"><h2>5 hari ke depan</h2><span>°C</span></div><div className="days">{weather?.daily.time.slice(0, 5).map((day, index) => <div className="day-row" key={day}><span>{formatDay(day, index)}</span><Icon aria-hidden="true" /><div className="range"><i style={{ left: `${((weather.daily.temperature_2m_min[index] - min) / range) * 100}%`, width: `${((weather.daily.temperature_2m_max[index] - weather.daily.temperature_2m_min[index]) / range) * 100}%` }} /></div><b>{Math.round(weather.daily.temperature_2m_max[index])}°</b><small>{Math.round(weather.daily.temperature_2m_min[index])}°</small></div>)}</div></section>
    <footer><span>Open-Meteo · OpenStreetMap</span><span>{updated ? `Diperbarui ${updated}` : 'Menunggu data'} · <Sunrise aria-hidden="true" /> {weather ? formatTime(weather.daily.sunrise[0]) : '—'} · <Sunset aria-hidden="true" /> {weather ? formatTime(weather.daily.sunset[0]) : '—'}</span></footer>
  </div></main>
}
